### PR TITLE
Adds entry macro

### LINKED ISSUE #1: hide the remaining unsafe part under the macro
Maybe we can hide the remaining unsafe part under the macro, use the macro to generate the real efi_main function, and then call main after processing the unsafe part like _start in C?

### PR DESCRIPTION
**Pull request by Aalivexy**
refer to https://github.com/ultimicro/zfi/issues/1

### CODE REVIEW

**Comment by ultimaweapon** [comment]
Better to use [attribute macro](https://doc.rust-lang.org/reference/procedural-macros.html#attribute-macros) will be better. On the user side it will be something like this:

```rust
#[zfi::main]
fn main() -> Status {
}
```

In order to do this you need to create a new crate and put it into a workspace member. My idea for a directory name is `macros` and the crate name is `zfi-macros` something like this:

```
.
├── Cargo.lock
├── Cargo.toml
├── COPYING
├── macros
│   ├── Cargo.toml
│   └── src
│       └── lib.rs
├── README.md
└── src
    ├── allocator.rs
    ├── boot.rs
    ├── console.rs
    ├── debug.rs
    ├── device.rs
    ├── event.rs
    ├── filesystem.rs
    ├── guid.rs
    ├── header.rs
    ├── image.rs
    ├── lib.rs
    ├── memory.rs
    ├── path.rs
    ├── pointer.rs
    ├── proto.rs
    ├── runtime.rs
    ├── status.rs
    ├── string.rs
    ├── system.rs
    └── time.rs
```

**Comment by Aalivexy** [comment]
I agree it looks better this way!
But because of my limited personal ability, I have to study the process macro, I haven't written it before XD

**Comment by Aalivexy** [comment]
But if you want to use workspace, it seems that zfi-macros also needs to be published to crates.io, and zfi crate and zfi-macros crate should belong to the same folder

**Comment by ultimaweapon** [comment]
Correct. You can use the structure like my previous comment. The `zfi` crate will be the [root package](https://doc.rust-lang.org/cargo/reference/workspaces.html#root-package) and `zfi-macros` will be a member.

**Pull request closed without merging**
